import { Experience, ExperienceStatus } from '../../domain/experience';
import { Country, Place, Region } from '../../domain/place';
import { BudgetBand, seasonMaskFromMonths, Tag } from '../../domain/taxonomy';

/**
 * A small, real, curated catalogue.
 *
 * A discovery product with an empty catalogue demos nothing, so the foundation
 * ships with genuine destinations (real coordinates, honest seasons) that are
 * deliberately spread across taste profiles — cold/solitary, warm/social,
 * desert, city, island — so recommendation ranking has something to actually
 * discriminate between. Media are placeholders until the media pipeline exists.
 */

const TS = '2026-01-01T00:00:00.000Z';

export const SEED_COUNTRIES: readonly Country[] = [
  { id: 'cty_no', code: 'NO', name: 'Norway', slug: 'norway' },
  { id: 'cty_is', code: 'IS', name: 'Iceland', slug: 'iceland' },
  { id: 'cty_jp', code: 'JP', name: 'Japan', slug: 'japan' },
  { id: 'cty_it', code: 'IT', name: 'Italy', slug: 'italy' },
  { id: 'cty_ma', code: 'MA', name: 'Morocco', slug: 'morocco' },
  { id: 'cty_pt', code: 'PT', name: 'Portugal', slug: 'portugal' },
  { id: 'cty_pe', code: 'PE', name: 'Peru', slug: 'peru' },
  { id: 'cty_nz', code: 'NZ', name: 'New Zealand', slug: 'new-zealand' },
];

export const SEED_REGIONS: readonly Region[] = [
  { id: 'rgn_lofoten', countryId: 'cty_no', name: 'Lofoten', slug: 'lofoten' },
  { id: 'rgn_south_iceland', countryId: 'cty_is', name: 'South Iceland', slug: 'south-iceland' },
  { id: 'rgn_kansai', countryId: 'cty_jp', name: 'Kansai', slug: 'kansai' },
  { id: 'rgn_dolomites', countryId: 'cty_it', name: 'Dolomites', slug: 'dolomites' },
  { id: 'rgn_sahara', countryId: 'cty_ma', name: 'Sahara', slug: 'sahara' },
  { id: 'rgn_algarve', countryId: 'cty_pt', name: 'Algarve', slug: 'algarve' },
  { id: 'rgn_cusco', countryId: 'cty_pe', name: 'Cusco', slug: 'cusco' },
  { id: 'rgn_otago', countryId: 'cty_nz', name: 'Otago', slug: 'otago' },
];

export const SEED_PLACES: readonly Place[] = [
  {
    id: 'plc_reine',
    countryId: 'cty_no',
    regionId: 'rgn_lofoten',
    name: 'Reine',
    slug: 'reine',
    coordinates: { lat: 67.9333, lng: 13.0894 },
    elevationMeters: 5,
    timezone: 'Europe/Oslo',
  },
  {
    id: 'plc_vestrahorn',
    countryId: 'cty_is',
    regionId: 'rgn_south_iceland',
    name: 'Vestrahorn',
    slug: 'vestrahorn',
    coordinates: { lat: 64.2494, lng: -14.9819 },
    elevationMeters: 454,
    timezone: 'Atlantic/Reykjavik',
  },
  {
    id: 'plc_arashiyama',
    countryId: 'cty_jp',
    regionId: 'rgn_kansai',
    name: 'Arashiyama',
    slug: 'arashiyama',
    coordinates: { lat: 35.0094, lng: 135.6668 },
    elevationMeters: 30,
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'plc_tre_cime',
    countryId: 'cty_it',
    regionId: 'rgn_dolomites',
    name: 'Tre Cime di Lavaredo',
    slug: 'tre-cime-di-lavaredo',
    coordinates: { lat: 46.6183, lng: 12.3053 },
    elevationMeters: 2320,
    timezone: 'Europe/Rome',
  },
  {
    id: 'plc_erg_chebbi',
    countryId: 'cty_ma',
    regionId: 'rgn_sahara',
    name: 'Erg Chebbi',
    slug: 'erg-chebbi',
    coordinates: { lat: 31.1497, lng: -3.9764 },
    elevationMeters: 800,
    timezone: 'Africa/Casablanca',
  },
  {
    id: 'plc_benagil',
    countryId: 'cty_pt',
    regionId: 'rgn_algarve',
    name: 'Benagil',
    slug: 'benagil',
    coordinates: { lat: 37.0876, lng: -8.4267 },
    elevationMeters: 20,
    timezone: 'Europe/Lisbon',
  },
  {
    id: 'plc_machu_picchu',
    countryId: 'cty_pe',
    regionId: 'rgn_cusco',
    name: 'Machu Picchu',
    slug: 'machu-picchu',
    coordinates: { lat: -13.1631, lng: -72.545 },
    elevationMeters: 2430,
    timezone: 'America/Lima',
  },
  {
    id: 'plc_wanaka',
    countryId: 'cty_nz',
    regionId: 'rgn_otago',
    name: 'Wanaka',
    slug: 'wanaka',
    coordinates: { lat: -44.7, lng: 169.15 },
    elevationMeters: 300,
    timezone: 'Pacific/Auckland',
  },
  {
    id: 'plc_kyoto_gion',
    countryId: 'cty_jp',
    regionId: 'rgn_kansai',
    name: 'Gion, Kyoto',
    slug: 'gion-kyoto',
    coordinates: { lat: 35.0037, lng: 135.7788 },
    elevationMeters: 45,
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'plc_hamnoy',
    countryId: 'cty_no',
    regionId: 'rgn_lofoten',
    name: 'Hamnøy',
    slug: 'hamnoy',
    coordinates: { lat: 67.9503, lng: 13.1372 },
    elevationMeters: 8,
    timezone: 'Europe/Oslo',
  },
];

function media(id: string, color: string): Experience['media'] {
  return [
    {
      id,
      url: `https://media.firo.app/seed/${id}.jpg`,
      dominantColor: color,
      width: 2400,
      height: 3000,
      attribution: null,
    },
  ];
}

export const SEED_EXPERIENCES: readonly Experience[] = [
  {
    id: 'exp_lofoten_blue_hour',
    placeId: 'plc_reine',
    slug: 'lofoten-blue-hour',
    title: 'Lofoten in the blue hour',
    summary: 'Red cabins, black water, and a sky that refuses to go fully dark.',
    story:
      'For a few weeks either side of midwinter the Lofoten islands sit in a long blue twilight. ' +
      'The peaks turn to silhouettes, the fjord goes to glass, and the whole archipelago feels ' +
      'like somewhere the world forgot to switch the lights on.',
    coordinates: { lat: 67.9333, lng: 13.0894 },
    tags: [Tag.COLD, Tag.MOUNTAINS, Tag.PHOTOGRAPHY, Tag.SOLITUDE, Tag.NATURE, Tag.WATER],
    budgetBand: BudgetBand.PREMIUM,
    seasonMask: seasonMaskFromMonths([1, 2, 3, 9, 10, 11, 12]),
    difficulty: 2,
    wowScore: 0.94,
    hiddenGemScore: 0.45,
    media: media('lofoten_blue_hour', '#1B2A3A'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_hamnoy_bridge_dawn',
    placeId: 'plc_hamnoy',
    slug: 'hamnoy-bridge-dawn',
    title: 'Dawn from the Hamnøy bridge',
    summary: 'The most photographed view in the Arctic — and still worth standing in the cold for.',
    story: null,
    coordinates: { lat: 67.9503, lng: 13.1372 },
    tags: [Tag.COLD, Tag.PHOTOGRAPHY, Tag.MOUNTAINS, Tag.WATER, Tag.SOLITUDE],
    budgetBand: BudgetBand.MODERATE,
    seasonMask: seasonMaskFromMonths([1, 2, 3, 10, 11, 12]),
    difficulty: 1,
    wowScore: 0.88,
    hiddenGemScore: 0.3,
    media: media('hamnoy_bridge_dawn', '#24384B'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_vestrahorn_black_sand',
    placeId: 'plc_vestrahorn',
    slug: 'vestrahorn-black-sand',
    title: 'Vestrahorn on black sand',
    summary: 'A jagged mountain rising straight out of a mirror of volcanic beach.',
    story:
      'Stokksnes is a rare place where a serious mountain meets a black sand beach with nothing ' +
      'in between. When the tide pulls back the sand mirrors the peaks, and in winter the ' +
      'northern lights sometimes finish the picture.',
    coordinates: { lat: 64.2494, lng: -14.9819 },
    tags: [Tag.COLD, Tag.MOUNTAINS, Tag.PHOTOGRAPHY, Tag.NATURE, Tag.SOLITUDE, Tag.BEACH],
    budgetBand: BudgetBand.MODERATE,
    seasonMask: seasonMaskFromMonths([1, 2, 3, 9, 10, 11, 12]),
    difficulty: 2,
    wowScore: 0.91,
    hiddenGemScore: 0.55,
    media: media('vestrahorn_black_sand', '#12181F'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_arashiyama_bamboo_dawn',
    placeId: 'plc_arashiyama',
    slug: 'arashiyama-bamboo-dawn',
    title: 'The bamboo grove before anyone wakes',
    summary: 'Get there at first light and the loudest thing is the creak of the stalks.',
    story: null,
    coordinates: { lat: 35.0094, lng: 135.6668 },
    tags: [Tag.CULTURE, Tag.NATURE, Tag.PHOTOGRAPHY, Tag.SOLITUDE, Tag.MINIMALISM],
    budgetBand: BudgetBand.MODERATE,
    seasonMask: seasonMaskFromMonths([3, 4, 5, 10, 11, 12]),
    difficulty: 1,
    wowScore: 0.82,
    hiddenGemScore: 0.2,
    media: media('arashiyama_bamboo_dawn', '#2C3B2A'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_gion_lantern_night',
    placeId: 'plc_kyoto_gion',
    slug: 'gion-lantern-night',
    title: 'Gion after the lanterns come on',
    summary: 'Wooden machiya, warm paper light, and the sound of geta on stone.',
    story: null,
    coordinates: { lat: 35.0037, lng: 135.7788 },
    tags: [Tag.CULTURE, Tag.CITY, Tag.FOOD, Tag.ARCHITECTURE, Tag.HISTORY, Tag.SOCIAL],
    budgetBand: BudgetBand.PREMIUM,
    seasonMask: seasonMaskFromMonths([3, 4, 5, 9, 10, 11]),
    difficulty: 1,
    wowScore: 0.79,
    hiddenGemScore: 0.25,
    media: media('gion_lantern_night', '#3B2418'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_tre_cime_circuit',
    placeId: 'plc_tre_cime',
    slug: 'tre-cime-circuit',
    title: 'The Tre Cime circuit',
    summary: 'Three impossible towers of rock, and a trail that keeps showing them to you.',
    story:
      'The loop around the Tre Cime is one of the great half-day walks in Europe: about ten ' +
      'kilometres, never technical, and the mountains rearrange themselves into a new composition ' +
      'at every bend.',
    coordinates: { lat: 46.6183, lng: 12.3053 },
    tags: [Tag.HIKING, Tag.MOUNTAINS, Tag.ADVENTURE, Tag.NATURE, Tag.PHOTOGRAPHY],
    budgetBand: BudgetBand.MODERATE,
    seasonMask: seasonMaskFromMonths([6, 7, 8, 9]),
    difficulty: 3,
    wowScore: 0.9,
    hiddenGemScore: 0.28,
    media: media('tre_cime_circuit', '#4A4E55'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_erg_chebbi_silence',
    placeId: 'plc_erg_chebbi',
    slug: 'erg-chebbi-silence',
    title: 'The silence of Erg Chebbi',
    summary: 'Dunes the height of buildings, and a quiet so complete it feels physical.',
    story: null,
    coordinates: { lat: 31.1497, lng: -3.9764 },
    tags: [Tag.DESERT, Tag.WARM, Tag.SOLITUDE, Tag.ADVENTURE, Tag.CAMPING, Tag.MINIMALISM],
    budgetBand: BudgetBand.BUDGET,
    seasonMask: seasonMaskFromMonths([1, 2, 3, 10, 11, 12]),
    difficulty: 3,
    wowScore: 0.87,
    hiddenGemScore: 0.62,
    media: media('erg_chebbi_silence', '#C08A4E'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_benagil_sea_cave',
    placeId: 'plc_benagil',
    slug: 'benagil-sea-cave',
    title: 'Kayaking into the Benagil cave',
    summary: 'A cathedral of golden stone with a hole in the roof and a beach on the floor.',
    story: null,
    coordinates: { lat: 37.0876, lng: -8.4267 },
    tags: [Tag.WATER, Tag.WARM, Tag.BEACH, Tag.ADVENTURE, Tag.SOCIAL, Tag.PHOTOGRAPHY],
    budgetBand: BudgetBand.BUDGET,
    seasonMask: seasonMaskFromMonths([5, 6, 7, 8, 9]),
    difficulty: 2,
    wowScore: 0.81,
    hiddenGemScore: 0.35,
    media: media('benagil_sea_cave', '#D2A15E'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_machu_picchu_first_light',
    placeId: 'plc_machu_picchu',
    slug: 'machu-picchu-first-light',
    title: 'Machu Picchu at first light',
    summary: 'Cloud pouring through the saddle while the terraces come out of the dark.',
    story: null,
    coordinates: { lat: -13.1631, lng: -72.545 },
    tags: [Tag.HISTORY, Tag.CULTURE, Tag.MOUNTAINS, Tag.HIKING, Tag.ADVENTURE, Tag.ARCHITECTURE],
    budgetBand: BudgetBand.PREMIUM,
    seasonMask: seasonMaskFromMonths([4, 5, 6, 7, 8, 9]),
    difficulty: 3,
    wowScore: 0.95,
    hiddenGemScore: 0.15,
    media: media('machu_picchu_first_light', '#3F5540'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'exp_wanaka_roy_peak',
    placeId: 'plc_wanaka',
    slug: 'wanaka-roys-peak',
    title: "Roy's Peak before sunrise",
    summary: 'A brutal climb in the dark that pays out over a lake the colour of mercury.',
    story: null,
    coordinates: { lat: -44.7, lng: 169.15 },
    tags: [Tag.HIKING, Tag.MOUNTAINS, Tag.ADVENTURE, Tag.NATURE, Tag.WATER, Tag.PHOTOGRAPHY],
    budgetBand: BudgetBand.MODERATE,
    seasonMask: seasonMaskFromMonths([11, 12, 1, 2, 3]),
    difficulty: 4,
    wowScore: 0.89,
    hiddenGemScore: 0.4,
    media: media('wanaka_roys_peak', '#5B6E7A'),
    status: ExperienceStatus.PUBLISHED,
    createdAt: TS,
    updatedAt: TS,
  },
];
